### 로그인 테스트

#POST http://localhost:8080/api/login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email":"fovena@gmail.com",
  "password":"member33!@"
}

### 로그인 테스트- 서버

POST http://3.34.122.155/api/login
Content-Type: application/json

{
  "email":"member8@mail.com",
  "password":"member33!@"
}



### 로그아웃 테스트
GET http://localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzNzQ5NDU4fQ._pvzJif01xSqtjBPjduJNzL71cH6KLWpdMun7cjbjaD-6E-XQgldeh40T9RgXXFyhHfH9wurwx8PvCedYOIuGA

### 로그아웃 테스트 - 서버
GET http://3.34.122.155/api/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXI4QG1haWwuY29tIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwibWVtYmVySWQiOjUxLCJleHAiOjE2MTM4MTY2Mzd9.MPF49mw8y6qEWmI5N1ZulXPgIHN_TyYjCby0KtX0gpCfx85vQIdOMblqqtMwdet2ytXmmNpJmYx-YQ18ZWcupA

### 회원가입 테스트

POST http://3.34.122.155/api/member
Content-Type: application/json

{
  "email":"member9@mail.com",
  "password":"member33!@",
  "passwordConfirm":"member33!@",
  "name":"한글",
  "birthDate": "2002-02-10",
  "contact":"01008551213"
}

###
POST http://localhost:8080/api/member
Content-Type: application/json

{
"email":"member11@mail.com",
"password":"password123",
"passwordConfirm":"password123",
"name":"테스터",
"birthDate": "1999-02-3",
"contact":"01008551213"
}

### 회원정보찾기 테스트

GET http://localhost:8080/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXIxMEBtYWlsLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsIm1lbWJlcklkIjo2MCwiZXhwIjoxNjEzODc0Mjg1fQ.9XF2bjJeK2p1ymHJ5TNRyaEZJSLTxg5mkAvEspZJoImShOuPQ-NteWlQF0d-k6CujQ3gyApTKnSTMPqgKldz2g

### 회원정보찾기 테스트 -서버

GET http://3.34.122.155/api/member/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsIm1lbWJlcklkIjoxLCJleHAiOjE2MTM1MzM0MDZ9.XmI9Vmfvc4FnH3Jv0pHgdZo6EG5d3ZPWpczWILksXTmmMjBmz8jSpI2UVcNQqWSXEkD_-17AnFc_yj-IqP-sww



### 회원정보수정 : 비밀번호변경

PUT http://localhost:8080/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzODgwNDk0fQ.MRQls_oiIS1VKtvOwSrF_TAsriHpd09pfgnFSn6CvYoxEaaUFpAHs2QNVIdf4uC8xrV_PXgSDRUpYwtgcam4Bw
Content-Type: application/json

{
  "password": "member33!@@"
}

### 회원정보수정 : 생년월일변경

PUT http://localhost:8080/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzODgwNDk0fQ.MRQls_oiIS1VKtvOwSrF_TAsriHpd09pfgnFSn6CvYoxEaaUFpAHs2QNVIdf4uC8xrV_PXgSDRUpYwtgcam4Bw
Content-Type: application/json

{
"birthDate": "1988-02-22"
}

### 회원탈퇴 테스트

DELETE http://3.34.122.155/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXI4QG1haWwuY29tIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwibWVtYmVySWQiOjUxLCJleHAiOjE2MTM4MTY3NTF9.52XzCklUC_R8sYD2Y8gDUx_hnpXfJLvslBleytzYdd7m5gWj78RV0cQGRIK30NuAiFfsX27hMT-kfzJHIpvT0g

### 구글로그인

### 중복회원용 회원가입
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "email":"fovena@gmail.com",
  "password":"member",
  "name":"name",
  "birthDate": "2020-02-03",
  "contact":"010-9908-5511"
}

### 회원가입 후 로그인
POST http://localhost:8080/api/login/google
Content-Type: application/json

{
  "email":"fovena@gmail.com",
  "socialId":"1234124123",
  "name":"name",
  "birthDate": "2020-02-03",
  "contact":"010-9908-5511"
}

