POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email":"member6@mail.com",
  "password":"member1"
}

###

POST http://localhost:8080/api/member
Content-Type: application/json

{
  "email":"member6@mail.com",
  "password":"member",
  "name":"name",
  "birthDate": "2020-02-03",
  "contact":"010-9908-5511"
   }

###

GET http://localhost:8080/api/member/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6MSwiZXhwIjoxNjEyNDQ4ODgxfQ.WgDayJ5Iz9ptnI_nS9CE7sn1GHMTYcGPC578PH7Me2aG6hh3XL-eO96rXmBbnqudl1Dc4y4kcigHK-r4Ik2Xnw

###

PUT http://localhost:8080/api/member/1
Content-Type: application/json

{
  "email":"member1@mail.com"

   }

###

PUT http://localhost:8080/api/member/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXI2QG1haWwuY29tIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwibWVtYmVySWQiOjYsImV4cCI6MTYxMjQ1OTAxMH0.P7YGvup0vxTafTlIpHM6e9re2cEFCejDMafpGSBiZS-hUNBfktphlc85FLlQAbSNyrcNkAtujb6mRRMoFTWJiQ
Content-Type: application/json

{
  "prePassword":"member1",
  "password": "member2"
}