### 로그인 테스트

#POST http://localhost:8080/api/login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email":"member@mail.com",
  "password":"member33!@"
}

### 로그인 테스트-testDB

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email":"test123@gmail.com",
  "password":"12345678a!"
}

### 로그인 테스트- 서버

POST http://3.34.122.155/api/login
Content-Type: application/json

{
  "email":"test123@gmail.com",
  "password":"12345678a!"
}



### 로그아웃 테스트
GET http://localhost:8080/api/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzNzQ5NDU4fQ._pvzJif01xSqtjBPjduJNzL71cH6KLWpdMun7cjbjaD-6E-XQgldeh40T9RgXXFyhHfH9wurwx8PvCedYOIuGA

### 로그아웃 테스트 - 서버
GET http://3.34.122.155/api/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsIm1lbWJlcklkIjoxLCJleHAiOjE2MTM1MzM0MDZ9.XmI9Vmfvc4FnH3Jv0pHgdZo6EG5d3ZPWpczWILksXTmmMjBmz8jSpI2UVcNQqWSXEkD_-17AnFc_yj-IqP-sww

### 회원가입 테스트

#POST http://localhost:8080/api/member
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "email":"member1@mail.com",
  "password":"member33!@",
  "name":"한글",
  "birthDate": "2002-02-10",
  "contact":"01008551213"
}

### 회원정보찾기 테스트

GET http://localhost:8080/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzNzQ5NDU4fQ._pvzJif01xSqtjBPjduJNzL71cH6KLWpdMun7cjbjaD-6E-XQgldeh40T9RgXXFyhHfH9wurwx8PvCedYOIuGA

### 회원정보찾기 테스트 -서버

GET http://3.34.122.155/api/member/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsIm1lbWJlcklkIjoxLCJleHAiOjE2MTM1MzM0MDZ9.XmI9Vmfvc4FnH3Jv0pHgdZo6EG5d3ZPWpczWILksXTmmMjBmz8jSpI2UVcNQqWSXEkD_-17AnFc_yj-IqP-sww



### 회원정보수정 : 비밀번호변경

PUT http://localhost:8080/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXJAbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6NywiZXhwIjoxNjEzODgwNDk0fQ.MRQls_oiIS1VKtvOwSrF_TAsriHpd09pfgnFSn6CvYoxEaaUFpAHs2QNVIdf4uC8xrV_PXgSDRUpYwtgcam4Bw
Content-Type: application/json

{
  "prePassword":"member33!@",
  "password": "member33!@@"
}

### 회원삭제 테스트

DELETE http://localhost:8080/api/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtZW1iZXIxQG1haWwuY29tIiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwibWVtYmVySWQiOjExLCJleHAiOjE2MTM4ODA2OTF9.MVnLS2vQf_LUB-rky4qzP82ZkONEoVk8bK8Ea4_98Rx9T-DmVOwoxUKMnnI07_S8vgsY3rLinh0XN9GQpznYVg

### 구글로그인

### 중복회원용 회원가입
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "email":"fovena@gmail.com",
  "password":"member",
  "name":"name",
  "birthDate": "2020-02-03",
  "contact":"010-9908-5511"
}

### 회원가입 후 로그인
POST http://localhost:8080/api/login/google
Content-Type: application/json

{
  "email":"fovena@gmail.com",
  "socialId":"1234124123",
  "name":"name",
  "birthDate": "2020-02-03",
  "contact":"010-9908-5511"
}

